apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  PersistentVolumeReclaimPolicy: Retain # or Delete or Recycle
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  # hostPath:
  #   path: /tmp/data
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4
