apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep2.0"] # Entrypoint on container
      args: ["10"] # CMD on container
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config
      env:
        - name: APP_COLOR
          value: pink
        - name: APP_COLOR
          valueFrom:
            secretKeyRef:
        - name: APP_COLOR
          valueFrom: 
            configMapKeyRef:
      volumes:
      - name: app-config-volume
        configMap:
          name: app-config
        
